### ISSUE TITLE
Android Navbar bp-action-overflow shows up for >= 3 icons

### ISSUE THREAD

**Issue by Goltergaul** [excellenteasy/bradypodion#103]
Hi the android navbar shows that submenu as soon as the navbar contains more then 3 action-icons.
This results in 2 icons beeing displayed and the dropdown with only one item in it. I think it would be better if the submenu would only appear for >= 4 icons. Why do I need a submenu if there is only one option in it? It would be better to just display the icon instead. Unfortunately this is hardcoded into the source of bradypodion so there is no chance to change it

**Comment by boennemann** [comment]
Hey @Goltergaul, 
that's indeed a bit illogical.

Do you think you can send a PR?
https://github.com/excellenteasy/bradypodion/blob/master/src/scripts/directives/navbar.js#L198

Best,
Stephan
