### ISSUE TITLE
Overview 0.3

### ISSUE THREAD

**Issue by davidpfahler** [excellenteasy/bradypodion#20]
# fixes
- [x] do not use delay on iscroll instantiation when no transition is happening (e.g. on app start)
- [ ] back button detection for paramtarized URLs
# features
- [ ] tabbar
- [ ] loading indicators
- [ ] button groups (segmented navbar)
- [ ] ng-swipe
- [ ] swipe back and forth gestures
- [ ] horizontal snapping swipe views
- [ ] detail disclosure
- [ ] image gallerys
- [ ] bp-navigation
- [ ] calender view
# for sencha touch 2 feature parity
### Table / iScroll
- [ ] pull to refresh
- [ ] load more (when scrolling to the end of a list)
- [ ] ABC navigation
### Forms
- [ ] sliders
- [ ] checkmark
### overlays
- [ ] action sheet
  others?
## tooling
- [ ] generator-bp-app
- [ ] phonegap build grunt tasks

**Comment by boennemann** [comment]
#25
