### ISSUE TITLE
Possible incompatibility of deps.js and ripple-phoneGap-Emulator

### ISSUE THREAD

**Issue by bpichon** [excellenteasy/bradypodion#28]
Error after installing the phoneGap-Emulator. Even if the Emulator is disabled.

![error](https://f.cloud.github.com/assets/4584375/944724/578851c4-02d2-11e3-88fa-a446c3577485.JPG)

Consequence is a white screen.
If you comment the 4 involved lines out, it seems to work normally.

**Comment by boennemann** [comment]
deps.js won't be used with bp > 0.2.5
