### ISSUE TITLE
Incorrect transformation to android (CELL+INPUT)

### ISSUE THREAD

**Issue by bpichon** [excellenteasy/bradypodion#31]
The text ('Größe', 'Alter') disappears.

How it looks like:
![androidinput](https://f.cloud.github.com/assets/4584375/1021183/d2689952-0ce7-11e3-90c9-88ee40c9c65d.JPG)

How it should look like:
![iosinput](https://f.cloud.github.com/assets/4584375/1021184/d2b8d75a-0ce7-11e3-96a1-3e3eea1773bf.JPG)

**Comment by boennemann** [comment]
duplicate #35
