### ISSUE TITLE
LaggyScroll

### ISSUE THREAD

**Issue by bpichon** [excellenteasy/bradypodion#32]
Build a page with few bp-tables (table-grouped).
If I want to scroll and put my scrolling-finger on a cell of a table which is "bp-tapable", it seems that the scroll isnt smooth anymore. The device thinks that i want to tap that cell. 
Same with bp-button.

**Comment by boennemann** [comment]
iScroll needs to be treated with caution when you want to have really slick performance. It is only needed in edge cases though and w/ 0.4.0 we have a native bp-scroll directive. Just use bp-scroll for now.
