### ISSUE TITLE
package.json contains caret symbol prefixing version numbers

### ISSUE THREAD

**Issue by lukebrowell** [excellenteasy/bradypodion#74]
package.json contains caret symbols prefixing version numbers, this syntax cannot be found here: https://www.npmjs.org/doc/files/package.json.html and appears to be causing errors. Is this an OS or encoding problem?

**Comment by boennemann** [comment]
Hello @dickensian,

thanks for reporting this issue to us.

We decided to change to carets in this commit 7508e0a as they are the new default for `npm install --save` with the latest stable node/npm distrubution. You can read more on this here: http://fredkschott.com/post/2014/02/npm-no-longer-defaults-to-tildes/

Could you please paste in the error this causes for you?

Stephan
