### ISSUE TITLE
up state detection fails when using parameters in the url

### ISSUE THREAD

**Issue by davidpfahler** [excellenteasy/bradypodion#84]
The idea of the up state detection simply using the second to last url parameter as the identifier of the up state name seems to break or at least get very awkward when using parameters in the route URL.

For example:
When on a state called "selectAccount" with the url `/clientList/:id/selectAccount`, `bp-navbar` directive will try to look up the state with name ":id".

I don't have a conceptual fix in mind right now, but will think about it. My current workaround is to just define an up state on the data object of the state for these cases.

**Comment by boennemann** [comment]
The fix would be to check if a state with that name even exists at this point: https://github.com/excellenteasy/bradypodion/blob/master/modules/scripts/directives/navbar.js#L123

We could detect that even earlier by checking for `urlsegment[0] != ':'`
