### ISSUE TITLE
bp-navbar-config issue with tabs

### ISSUE THREAD

**Issue by Goltergaul** [excellenteasy/bradypodion#96]
hi i have two tabs in my app and in every tab view i have a bp-navbar-config element.

When i click on a tab the navbar changes correctly, but if i switch to the other tab the configs seems to be not used anymore. however if i switch between the two tabs a few times the missing actions in the navbar reappear and also stay regardless which tab i click.

any hints what could be wrong? Both tabs use the same view template and controller

**Comment by davidpfahler** [comment]
Can you post a jsfiddle or similar of the code you are using? I can not really picture the problem or the setup you have. Thanks.

**Comment by Goltergaul** [comment]
```
$stateProvider
  .state('alerts', {
    url: '/',
    templateUrl: 'views/alerts.html',
    data: {
      title: 'Alerts'
    }
  }).state('unreadAlerts', {
    parent: 'alerts',
    url: 'alerts/unread',
    templateUrl: 'views/alerts/list.html',
    controller: 'AlertsCtrl',
    data: {
      transition: 'fade'
    }
  }).state('readAlerts', {
    parent: 'alerts',
    url: 'alerts/read',
    templateUrl: 'views/alerts/list.html',
    controller: 'AlertsCtrl',
    data: {
      transition: 'fade'
    }
  })
```

Alerts view:

```
<bp-tabbar>
  <bp-tab
    ui-sref='unreadAlerts'
    bp-tab-icon="icon-inbox"
    bp-tab-title="Ungelesene Alerts">
  </bp-tab>
  <bp-tab
    ui-sref='readAlerts'
    bp-tab-icon="icon-inbox"
    bp-tab-title="Gelesene Alerts">
  </bp-tab>
</bp-tabbar>

<bp-content>
  <div ui-view></div>
</bp-content>
```

List view:

```
<div class='bp-content'>
  <bp-table bp-iscroll>
    <bp-cell class="bp-cell alert-cell" ng-repeat="alert in alerts | filter:alertsFilter">
      ...
    </bp-cell>
  </bp-table>
</div>

<bp-navbar-config>
  <bp-action ng-click="toggleTheme()" class="fa-exchange">Theme</bp-action>
  <bp-action ng-click="action()" bp-tab="action()" login class="fa-sign-in">Login</bp-action>
</bp-navbar-config>
```

the two bp-actions disappear and reapear as described. also they do not respond do the ng-click event after they reappear.

maybe i can make a fiddle later. Maybe you can spot the cause without it :)

**Comment by davidpfahler** [comment]
Your state config is what comes to my mind first. I cannot remember if we ever tested this with nested states. Usually we don't need them in mobile apps, we have found. But also your URLs aren't following the conventions. The combination of that might cause unexpected behavior. Also, please try putting the `bp-navbar-config` element first and the `bp-tabbar` element last. Let me know if that does anything.

**Comment by Goltergaul** [comment]
i solved the issue an other way, so i could not test what you suggested :/ but thanks for the help anyway!
